[workspace]
members = ["bsp"]

[package]
edition      = "2021"
name         = "esp_slint"
rust-version = "1.88"
version      = "0.1.0"
build        = "build.rs"
autoexamples = false

[dependencies]
embassy-executor = "0.10.0"
embassy-time = "0.5.0"
esp-alloc = "0.10.0"
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3"] }
esp-hal = { version = "1.1.1", features = ["esp32s3", "unstable"] }
esp-println = { version = "0.17.0", features = ["esp32s3", "log-04"] }
esp-rtos = { version = "0.3.0", features = [
    "esp32s3",
    "esp-radio",
    "embassy",
    "log-04",
] }
esp_slint_bsp = { path = "bsp" }
slint = { version = "=1.16.0", default-features = false, features = [
    "compat-1-2",
    "unsafe-single-threaded",
    "libm",
    "renderer-software",
] }

[features]
default = ["wifi", "ble"]
wifi = ["esp_slint_bsp/wifi"]
ble = ["esp_slint_bsp/ble"]
full = ["wifi", "ble"]

[build-dependencies]
slint-build = "=1.16.0"

[profile.dev.package.esp-radio]
opt-level = 3

[profile.dev.package.esp-radio-rtos-driver]
opt-level = 3

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units    = 1
debug            = 0
strip            = "debuginfo"
debug-assertions = false
incremental      = false
lto              = "fat"
opt-level        = "z"
overflow-checks  = false
panic            = "abort"
